### ISSUE TITLE
Advantages of using this plugin?

### ISSUE THREAD

**Issue by suits-at** [gethypervisual/gridsome-plugin-netlify-cms#2]
What is the advantage of using this plugin? Why shouldn't I simply add netlify-cms to any gridsome project on my own, like described in the [official documentation](https://www.netlifycms.org/docs/add-to-your-site/)?

**Comment by tobymarsden** [comment]
@suits-at You can follow the first section of the official docs by dumping an `index.html` file into your `static` folder, and that will work OK, though it's not very customizable.

This plugin makes it considerably easier to install via NPM, which gives you the most flexibility -- it'll build your Netlify CMS module both in development and production. I'll add this to the README to make it clearer.

Soon, this plugin will also let you bring your site styles into the preview pane, which makes a big difference.

**Comment by suits-at** [comment]
One advantage of installing netlify-cms via npm is of course that you can update the package via `npm update` instead of having to manually update the CDN link to the newest version number of netlify-cms. But of which other customization-advantages are you speaking of?

What for should I need netfliy-cms in my local development environment? Its meant to be used to update content - so I don't see any difference of doing this locally or via the URL of the deployed website, without an internet connection I can't push changes anyways.

> Soon, this plugin will also let you bring your site styles into the preview pane, which makes a big difference.

This sounds promising. But isn't this feature more an extension to the netlify-cms itself? IMO this has nothing to do with gridsome, does it?

**Comment by tobymarsden** [comment]
@suits-at Using the npm module means you're bringing in widgets and registering custom preview templates without relying on globals -- and you can use any other npm modules here, and not just those that export globals when included via script tag. 

You'll get away with using a static `index.html` for the most basic configuration, though. If it works for you, carry on!

I use Netlify CMS in development to test how new CSS or templates work with arbitrary content changes -- I have my development environment set up to automatically sync changes locally following the git commit. It's kind-of magical. 

> This sounds promising. But isn't this feature more an extension to the netlify-cms itself? IMO this has nothing to do with gridsome, does it?

It's more related to Gridsome than Netlify CMS, because it's Gridsome that builds your site CSS -- where I'm trying to get to is to have this plugin bring the relevant site CSS (and even the correct Vue 'template' components from Gridsome!) into the preview pane. I have both of these working here but it remains to be seen how robust it is across different Gridsome instances.

**Comment by suits-at** [comment]
Thanks for clarification @tobymarsden. It seems you have some other usecases than I have. I will carry on using the static file for now, and maybe include it via npm sometimes if needed.

**Comment by tobymarsden** [comment]
@suits-at You can even use some of the non-core Netlify CMS widgets without setting them up in a module, and just including the scripts in your index.html and linking them up via globals. It's really when you want to see styled previews or using custom widgets that you'll want to bite the bullet and use a module.

**Comment by suits-at** [comment]
I use netlify cms just as an easy way to create some content. Therefore I don't need styled previews or custom widgets at all. But thanks for your insights! :)
