### ISSUE TITLE
Location of Netlify config.yml

### ISSUE THREAD

**Issue by dizid** [gethypervisual/gridsome-plugin-netlify-cms#7]
[Netlify](https://www.netlifycms.org/docs/add-to-your-site/#configuration) states that it's config.yml needs to go in the 'static file location'.
For Gridsome this should be:  /static

In the [docs](https://gridsome.org/plugins/gridsome-plugin-netlify-cms) for gridsome-plugin-netlify-cms it says "Then add your Netlify CMS configuration file in src/admin/config.yml"

Could this be a documentation error or am i missing something?

**Comment by tobymarsden** [comment]
@dizid `gridsome-plugin-netlify-cms` serves the `config.yml` file from your `src/admin/` directory (copying it to the correct folder in `dist` for production), so that's the place to have it. The Netlify docs refer to setting up the CMS manually. If you're not seeing it available when placed in `src/admin`, let me know!
